### PR TITLE
Title text does not contain markup.

### PR DESCRIPTION
**Pull request by redndahead**
When the tabs get turned to accordions the titles don't retain their markup.  It's important that they do.  One line easy fix.

### CODE REVIEW

**Comment by samsono** [comment]
@redndahead, In line no.43 we are generating the h2 Markup. so we are using text() method to get the titles from tab to place in accordion title section.

**Comment by redndahead** [comment]
Correct, this grabs all the html within the title and throws it within the h2.  Sometimes there is important markup within the title.  For example < strong > and < em > tags.

**Comment by samsono** [comment]
Yes I agree, good find. Thanks :)

**Comment by redndahead** [comment]
Thanks! Great library.

**Pull request merged**
